Repository normcontrol/normcontrol-Document-Parser, pull requests merged in 2023-03, with the labels that each got.

#18 [Feat] Add docsify.js (https://docsify.js.org/) as documentation system
  docs/.nojekyll
  docs/README.md
  docs/_sidebar.md
  docs/about/arhitect.md
  docs/about/description.md
  docs/classes/index.md
  docs/docx/index.md
  docs/docx/paragraph.md
  docs/get_started.md
  docs/index.html
  docs/odt/index.md
  docs/odt/paragraph.md
  docs/pdf/index.md
  docs/pdf/paragraph.md
Labels: documentation, enhancement

#26 [Feat]Added the dataclasses functionality to the main unified classes.
  src/Class/DocumentClass.py
  src/Helpers/Enums/AlignmentEnum.py
  src/Helpers/measurement.py
  src/PDF/Line.py
  src/PDF/PdfParagraph.py
  src/PDF/TestPDFParser/Отчёт по практике для парсинга.pdf
  src/PDF/test.pdf
  src/classes/DocumentClass.py
  src/classes/DrawFrame.py
  src/classes/Paragraph.py
  src/classes/Table.py
  src/classes/TableCell.py
  src/classes/TableColumn.py
  src/classes/TableRow.py
  src/pdf/pdfclasses/Line.py
  src/pdf/pdfclasses/PdfParagraph.py
  src/pdf/pdfclasses/Table.py
Labels: documentation, critical

#35 Create python-app.yml
  .github/workflows/tests-app.yml
  requirements.txt
  src/doc/DocxParagraph.py
  src/doc/README.MD
  src/doc/__init__.py
  src/doc/examples/paragraphParser.py
  src/doc/helpers/StylePropertyCoverage.py
  src/doc/helpers/__init__.py
  src/doc/temp/Paragraph.py
  src/doc/temp/__init__.py
  src/tests/__init__.py
  src/tests/docx/test_DocxParagraph.py
Labels: enhancement

#27 [Feat]: updating the architecture of the ODT document parsing module
  src/__init__.py
  src/classes/DrawFrame.py
  src/classes/Table.py
  src/classes/TableCell.py
  src/classes/TableColumn.py
  src/classes/TableRow.py
  src/helpers/Enums/AlignmentEnum.py
  src/helpers/__init__.py
  src/helpers/measurement.py
  src/helpers/odt/__init__.py
  src/helpers/odt/consts.py
  src/helpers/odt/path.py
  src/helpers/odt/timing.py
  src/odt/ODTParser.py
  src/odt/__init__.py
  src/odt/elements/AutomaticStylesParser.py
  src/odt/elements/DefaultStylesParser.py
  src/odt/elements/ImagesParser.py
  src/odt/elements/ListsParser.py
  src/odt/elements/NodesParser.py
  src/odt/elements/ODTDocument.py
  src/odt/elements/ParagraphsParser.py
  src/odt/elements/RegularStylesParser.py
  src/odt/elements/TablesParser.py
  src/odt/elements/__init__.py
  src/odt/examples/imageParser.py
  src/odt/examples/listParser.py
  src/odt/examples/parserScript.py
  src/odt/examples/parsing_images.py
  src/odt/examples/parsing_lists.py
  src/odt/examples/parsing_styles.py
  src/odt/examples/parsing_tables.py
  src/odt/examples/tableParser.py
  src/odt/styles/Auto.py
  src/odt/styles/Default.py
  src/odt/styles/Style.py
Labels: enhancement, critical, odt

#44 [Feat]: Added the first version of documentation for ODT parsing
  docs/_sidebar.md
  docs/assets/images/ODTElements1.png
  docs/assets/images/ODTElements2.png
  docs/assets/images/ODTStructure.png
  docs/odt/elements.md
  docs/odt/index.md
  docs/odt/paragraph.md
Labels: documentation, odt

#49 [Fix]: Updated common element classes
  src/classes/Frame.py
  src/classes/Image.py
  src/classes/List.py
  src/classes/Paragraph.py
  src/classes/Table.py
  src/classes/TableCell.py
  src/classes/TableColumn.py
  src/classes/TableRow.py
  src/classes/UnifiedDocumentView.py
Labels: enhancement
